name = "receptia-worker"
main = "src/index.ts"
compatibility_date = "2025-08-14"

# (optionnel) servir des fichiers statiques depuis un dossier
# mets ton build/static ici si tu en as
[assets]
directory = "public"   # ou "dist" si tu as un build

# ENV DE PRODUCTION
[env.prod]
routes = [
  { pattern = "receptia.fr/*", zone_name = "receptia.fr" }
]

# ENV DE DEV / PREPROD (optionnel)
[env.dev]
routes = [
  { pattern = "dev.receptia.fr/*", zone_name = "receptia.fr" }
]